version: '3'
services:
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - 3306:3306

  sample_rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_rails_app
    command: /bin/sh -c "rm -f /sample_rails_app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000 -e development"
    volumes:
      - .:/sample_rails_app:cached
      - bundle:/bundle
    ports:
      - 3080:3000
    depends_on:
      - db

volumes:
  bundle:
    driver: local
